<?php
/*******************************************
 *
 * Ingeniería Informática - PW - David Martín Cerezo - 2024
 *
 *******************************************
 *
 *  Pie de pagina para toda la web
 *
 ******************************************************************************/
?>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<footer>
    <p>Realizado por <span><a href="<?= BASE_URL ?>html/contacto.html">D. Martín Cerezo </a></span>©.&nbsp;&nbsp;&nbsp;<a href="https://github.com/DmCerezo"><i class="fa fa-github" style="color:white;font-size:15px;text-alig:center"></i></a> </p>
    <span><a href="<?= BASE_URL ?>como_se_hizo.pdf">¿Como se hizo?</a></span>
</footer>
